// Generated by gencpp from file map_annotator/PoseNames.msg
// DO NOT EDIT!


#ifndef MAP_ANNOTATOR_MESSAGE_POSENAMES_H
#define MAP_ANNOTATOR_MESSAGE_POSENAMES_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace map_annotator
{
template <class ContainerAllocator>
struct PoseNames_
{
  typedef PoseNames_<ContainerAllocator> Type;

  PoseNames_()
    : names()  {
    }
  PoseNames_(const ContainerAllocator& _alloc)
    : names(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > , typename ContainerAllocator::template rebind<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::other >  _names_type;
  _names_type names;





  typedef boost::shared_ptr< ::map_annotator::PoseNames_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::map_annotator::PoseNames_<ContainerAllocator> const> ConstPtr;

}; // struct PoseNames_

typedef ::map_annotator::PoseNames_<std::allocator<void> > PoseNames;

typedef boost::shared_ptr< ::map_annotator::PoseNames > PoseNamesPtr;
typedef boost::shared_ptr< ::map_annotator::PoseNames const> PoseNamesConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::map_annotator::PoseNames_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::map_annotator::PoseNames_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace map_annotator

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'map_annotator': ['/home/jzhang102/Documents/humanoid_proj/proj_ros_ws/src/cse481wi18/map_annotator/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::map_annotator::PoseNames_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::map_annotator::PoseNames_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::map_annotator::PoseNames_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::map_annotator::PoseNames_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::map_annotator::PoseNames_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::map_annotator::PoseNames_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::map_annotator::PoseNames_<ContainerAllocator> >
{
  static const char* value()
  {
    return "dc7ae3609524b18034e49294a4ce670e";
  }

  static const char* value(const ::map_annotator::PoseNames_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xdc7ae3609524b180ULL;
  static const uint64_t static_value2 = 0x34e49294a4ce670eULL;
};

template<class ContainerAllocator>
struct DataType< ::map_annotator::PoseNames_<ContainerAllocator> >
{
  static const char* value()
  {
    return "map_annotator/PoseNames";
  }

  static const char* value(const ::map_annotator::PoseNames_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::map_annotator::PoseNames_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string[] names\n\
";
  }

  static const char* value(const ::map_annotator::PoseNames_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::map_annotator::PoseNames_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.names);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PoseNames_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::map_annotator::PoseNames_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::map_annotator::PoseNames_<ContainerAllocator>& v)
  {
    s << indent << "names[]" << std::endl;
    for (size_t i = 0; i < v.names.size(); ++i)
    {
      s << indent << "  names[" << i << "]: ";
      Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.names[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // MAP_ANNOTATOR_MESSAGE_POSENAMES_H
