// Generated by gencpp from file map_annotator/UserAction.msg
// DO NOT EDIT!


#ifndef MAP_ANNOTATOR_MESSAGE_USERACTION_H
#define MAP_ANNOTATOR_MESSAGE_USERACTION_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace map_annotator
{
template <class ContainerAllocator>
struct UserAction_
{
  typedef UserAction_<ContainerAllocator> Type;

  UserAction_()
    : command()
    , name()
    , updated_name()  {
    }
  UserAction_(const ContainerAllocator& _alloc)
    : command(_alloc)
    , name(_alloc)
    , updated_name(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _command_type;
  _command_type command;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _name_type;
  _name_type name;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _updated_name_type;
  _updated_name_type updated_name;




  static const std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  CREATE;
  static const std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  DELETE;
  static const std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  GOTO;
  static const std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  RENAME;

  typedef boost::shared_ptr< ::map_annotator::UserAction_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::map_annotator::UserAction_<ContainerAllocator> const> ConstPtr;

}; // struct UserAction_

typedef ::map_annotator::UserAction_<std::allocator<void> > UserAction;

typedef boost::shared_ptr< ::map_annotator::UserAction > UserActionPtr;
typedef boost::shared_ptr< ::map_annotator::UserAction const> UserActionConstPtr;

// constants requiring out of line definition

   
   template<typename ContainerAllocator> const std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > 
      UserAction_<ContainerAllocator>::CREATE =
        
          "create"
        
        ;
   

   
   template<typename ContainerAllocator> const std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > 
      UserAction_<ContainerAllocator>::DELETE =
        
          "delete"
        
        ;
   

   
   template<typename ContainerAllocator> const std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > 
      UserAction_<ContainerAllocator>::GOTO =
        
          "goto"
        
        ;
   

   
   template<typename ContainerAllocator> const std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > 
      UserAction_<ContainerAllocator>::RENAME =
        
          "rename"
        
        ;
   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::map_annotator::UserAction_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::map_annotator::UserAction_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace map_annotator

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'map_annotator': ['/home/jzhang102/Documents/humanoid_proj/proj_ros_ws/src/cse481wi18/map_annotator/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::map_annotator::UserAction_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::map_annotator::UserAction_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::map_annotator::UserAction_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::map_annotator::UserAction_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::map_annotator::UserAction_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::map_annotator::UserAction_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::map_annotator::UserAction_<ContainerAllocator> >
{
  static const char* value()
  {
    return "02b53ace3ff4f0b2c6988ccd36fc2910";
  }

  static const char* value(const ::map_annotator::UserAction_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x02b53ace3ff4f0b2ULL;
  static const uint64_t static_value2 = 0xc6988ccd36fc2910ULL;
};

template<class ContainerAllocator>
struct DataType< ::map_annotator::UserAction_<ContainerAllocator> >
{
  static const char* value()
  {
    return "map_annotator/UserAction";
  }

  static const char* value(const ::map_annotator::UserAction_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::map_annotator::UserAction_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string CREATE=create\n\
string DELETE=delete\n\
string GOTO=goto\n\
string RENAME=rename\n\
string command\n\
string name # The name of the pose the command applies to\n\
string updated_name # If command is RENAME, this is the new name of the pose\n\
";
  }

  static const char* value(const ::map_annotator::UserAction_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::map_annotator::UserAction_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.command);
      stream.next(m.name);
      stream.next(m.updated_name);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct UserAction_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::map_annotator::UserAction_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::map_annotator::UserAction_<ContainerAllocator>& v)
  {
    s << indent << "command: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.command);
    s << indent << "name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.name);
    s << indent << "updated_name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.updated_name);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MAP_ANNOTATOR_MESSAGE_USERACTION_H
