// Generated by gencpp from file perception_msgs/ObjectFeatures.msg
// DO NOT EDIT!


#ifndef PERCEPTION_MSGS_MESSAGE_OBJECTFEATURES_H
#define PERCEPTION_MSGS_MESSAGE_OBJECTFEATURES_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace perception_msgs
{
template <class ContainerAllocator>
struct ObjectFeatures_
{
  typedef ObjectFeatures_<ContainerAllocator> Type;

  ObjectFeatures_()
    : object_name()
    , names()
    , values()  {
    }
  ObjectFeatures_(const ContainerAllocator& _alloc)
    : object_name(_alloc)
    , names(_alloc)
    , values(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _object_name_type;
  _object_name_type object_name;

   typedef std::vector<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > , typename ContainerAllocator::template rebind<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::other >  _names_type;
  _names_type names;

   typedef std::vector<double, typename ContainerAllocator::template rebind<double>::other >  _values_type;
  _values_type values;





  typedef boost::shared_ptr< ::perception_msgs::ObjectFeatures_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::perception_msgs::ObjectFeatures_<ContainerAllocator> const> ConstPtr;

}; // struct ObjectFeatures_

typedef ::perception_msgs::ObjectFeatures_<std::allocator<void> > ObjectFeatures;

typedef boost::shared_ptr< ::perception_msgs::ObjectFeatures > ObjectFeaturesPtr;
typedef boost::shared_ptr< ::perception_msgs::ObjectFeatures const> ObjectFeaturesConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::perception_msgs::ObjectFeatures_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::perception_msgs::ObjectFeatures_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace perception_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'perception_msgs': ['/home/jzhang102/Documents/humanoid_proj/proj_ros_ws/src/cse481wi18/perception_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::perception_msgs::ObjectFeatures_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::perception_msgs::ObjectFeatures_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::perception_msgs::ObjectFeatures_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::perception_msgs::ObjectFeatures_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::perception_msgs::ObjectFeatures_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::perception_msgs::ObjectFeatures_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::perception_msgs::ObjectFeatures_<ContainerAllocator> >
{
  static const char* value()
  {
    return "fe6a1b3ba02e62219365f96560d5f759";
  }

  static const char* value(const ::perception_msgs::ObjectFeatures_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xfe6a1b3ba02e6221ULL;
  static const uint64_t static_value2 = 0x9365f96560d5f759ULL;
};

template<class ContainerAllocator>
struct DataType< ::perception_msgs::ObjectFeatures_<ContainerAllocator> >
{
  static const char* value()
  {
    return "perception_msgs/ObjectFeatures";
  }

  static const char* value(const ::perception_msgs::ObjectFeatures_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::perception_msgs::ObjectFeatures_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string object_name\n\
string[] names\n\
float64[] values\n\
";
  }

  static const char* value(const ::perception_msgs::ObjectFeatures_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::perception_msgs::ObjectFeatures_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.object_name);
      stream.next(m.names);
      stream.next(m.values);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ObjectFeatures_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::perception_msgs::ObjectFeatures_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::perception_msgs::ObjectFeatures_<ContainerAllocator>& v)
  {
    s << indent << "object_name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.object_name);
    s << indent << "names[]" << std::endl;
    for (size_t i = 0; i < v.names.size(); ++i)
    {
      s << indent << "  names[" << i << "]: ";
      Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.names[i]);
    }
    s << indent << "values[]" << std::endl;
    for (size_t i = 0; i < v.values.size(); ++i)
    {
      s << indent << "  values[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.values[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // PERCEPTION_MSGS_MESSAGE_OBJECTFEATURES_H
